[phases.setup]
nixPkgs = ['nodejs-20_x', 'php81']

[phases.install]
dependsOn = ['setup']
cmds = [
  "php -r \"copy('https://getcomposer.org/installer', 'composer-setup.php');\"",
  "php composer-setup.php",
  "php -r \"unlink('composer-setup.php');\"",
  "chmod +x composer.phar",
  "php composer.phar --version"
]

[phases.build]
dependsOn = ['install']
cmds = ['chmod +x build.sh && ./build.sh']

[start]
cmd = 'cd backend && php artisan serve --host=0.0.0.0 --port=$PORT'

