[phases.setup]
nixPkgs = ['nodejs-18_x', 'php81', 'composer']

[phases.build]
dependsOn = ['setup']
cmds = ['chmod +x build.sh && ./build.sh']

[start]
cmd = 'cd backend && php artisan serve --host=0.0.0.0 --port=$PORT'

